name: "build"
on: ["push"]
jobs:
  build-and-publish:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v2"
    - name: "Set up java"
      uses: "actions/setup-java@v6"
      with:
        distribution: "redhat"
        java-version: "21.0.8"
    - name: "Build"
      id: "build"
      run: "make"
    - name: "Version"
      id: "version"
      run: echo "::set-output name=version::$(make version)"
    - name: "Check for Existing Release"
      id: "check-release"
      uses: mukunku/release-exists-action@v1.1.0
      with:
        tag: ${{ steps.version.outputs.version }}
    - name: "Publish"
      if: github.ref == 'refs/heads/main' && steps.check-release.outputs.exists == 'false'
      uses: "ncipollo/release-action@v1"
      with:
        name: ${{ steps.version.outputs.version }}
        tag: ${{ steps.version.outputs.version }}
        omitBody: true
        artifacts: "build/ScimmaAuthPlugin.jar"
        token: ${{ secrets.GITHUB_TOKEN }}
